from pathlib import Path


def replace_between(path: str, start_marker: str, end_marker: str, replacement: str, label: str) -> None:
    file = Path(path)
    source = file.read_text(encoding="utf-8")
    start = source.index(start_marker)
    end = source.index(end_marker, start)
    file.write_text(source[:start] + replacement + source[end:], encoding="utf-8")


def replace_once(path: str, old: str, new: str, label: str) -> None:
    file = Path(path)
    source = file.read_text(encoding="utf-8")
    count = source.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match in {path}, got {count}")
    file.write_text(source.replace(old, new, 1), encoding="utf-8")


NOTE_LINKS = r'''/**
 * Note and block backlink extraction.
 *
 * Tiptap links inherit the closest supported node blockId. Markdown links use
 * the persisted `^blk_xxx` suffix generated by noteBlocks.ts, so both editors
 * produce sourceBlockId + targetBlockId relations.
 */
import type Database from "better-sqlite3";
import { noteLinksRepository } from "../repositories";
import type { NoteLinkEntry } from "../repositories";
import { hasPermission, resolveNotePermission } from "../middleware/acl";

const NOTE_LINK_RE = /\[\[note:([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})(?:#blk:([a-zA-Z0-9_-]+))?(?:\|([^\]]*))?\]\]/g;
const NOTE_HREF_RE = /note:([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})(?:#blk:([a-zA-Z0-9_-]+))?/g;
const SOURCE_BLOCK_TYPES = new Set(["heading", "paragraph", "listItem", "taskItem", "blockquote", "codeBlock"]);
const MARKDOWN_BLOCK_ID_RE = /(?:\s+|^)\^(blk_[A-Za-z0-9_-]{6,})\s*$/;

function addEntry(entries: NoteLinkEntry[], seen: Set<string>, entry: NoteLinkEntry): void {
  const key = `${entry.sourceBlockId || ""}:${entry.targetNoteId}:${entry.targetBlockId || ""}`;
  if (seen.has(key)) return;
  seen.add(key);
  entries.push(entry);
}

function entriesFromText(
  text: string,
  sourceBlockId: string | null,
  entries: NoteLinkEntry[],
  seen: Set<string>,
): void {
  const excerpt = text.replace(MARKDOWN_BLOCK_ID_RE, "").replace(/\s+/g, " ").trim().slice(0, 240) || null;
  for (const match of text.matchAll(NOTE_LINK_RE)) {
    const targetNoteId = match[1].toLowerCase();
    const targetBlockId = match[2] || null;
    const displayText = match[3] || null;
    addEntry(entries, seen, {
      targetNoteId,
      targetBlockId,
      sourceBlockId,
      linkType: targetBlockId ? "block" : "note",
      linkText: displayText,
      excerpt: excerpt || displayText,
    });
  }
  for (const match of text.matchAll(NOTE_HREF_RE)) {
    const targetNoteId = match[1].toLowerCase();
    const targetBlockId = match[2] || null;
    addEntry(entries, seen, {
      targetNoteId,
      targetBlockId,
      sourceBlockId,
      linkType: targetBlockId ? "block" : "note",
      linkText: null,
      excerpt,
    });
  }
}

function isMarkdownStandaloneBlock(line: string): boolean {
  return (
    /^\s{0,3}#{1,6}\s+/.test(line) ||
    /^\s*[-*+]\s+\[[ xX]\]\s+/.test(line) ||
    /^\s*(?:[-*+]|\d+\.)\s+/.test(line) ||
    /^\s{0,3}>\s?/.test(line) ||
    /^\s*(```+|~~~+)/.test(line)
  );
}

function extractMarkdownLinks(content: string, entries: NoteLinkEntry[], seen: Set<string>): void {
  const lines = content.split("\n");
  let index = 0;
  while (index < lines.length) {
    if (!lines[index].trim()) {
      index += 1;
      continue;
    }

    const start = index;
    const fence = lines[index].match(/^\s*(```+|~~~+)/);
    if (fence) {
      const marker = fence[1];
      index += 1;
      while (index < lines.length && !new RegExp(`^\\s*${marker[0]}{${marker.length},}\\s*$`).test(lines[index])) {
        index += 1;
      }
      if (index < lines.length) index += 1;
      if (index < lines.length && /^\s*\^blk_[A-Za-z0-9_-]{6,}\s*$/.test(lines[index])) index += 1;
    } else if (isMarkdownStandaloneBlock(lines[index])) {
      index += 1;
    } else {
      index += 1;
      while (
        index < lines.length &&
        lines[index].trim() &&
        !isMarkdownStandaloneBlock(lines[index])
      ) {
        index += 1;
      }
    }

    const blockText = lines.slice(start, index).join("\n");
    const idMatch = blockText.match(MARKDOWN_BLOCK_ID_RE);
    entriesFromText(blockText, idMatch?.[1] || null, entries, seen);
  }
}

export function extractNoteLinksFromContent(content: string): NoteLinkEntry[] {
  const entries: NoteLinkEntry[] = [];
  const seen = new Set<string>();
  try {
    const doc = JSON.parse(content);
    if (doc && typeof doc === "object" && Array.isArray(doc.content)) {
      const visit = (nodes: any[], parentBlockId: string | null) => {
        for (const node of nodes) {
          if (!node || typeof node !== "object") continue;
          const ownBlockId = SOURCE_BLOCK_TYPES.has(node.type) && typeof node.attrs?.blockId === "string"
            ? node.attrs.blockId
            : parentBlockId;
          if (node.type === "text") {
            const text = String(node.text || "");
            entriesFromText(text, ownBlockId, entries, seen);
            for (const mark of Array.isArray(node.marks) ? node.marks : []) {
              const href = mark?.attrs?.href;
              if (mark?.type === "link" && typeof href === "string" && href.startsWith("note:")) {
                entriesFromText(href, ownBlockId, entries, seen);
              }
            }
          }
          if (Array.isArray(node.content)) visit(node.content, ownBlockId);
        }
      };
      visit(doc.content, null);
      return entries;
    }
  } catch {
    // Markdown / HTML fallback below.
  }

  if (/^\s*(?:<!doctype\s+html|<html\b|<[a-z][^>]*>)/i.test(content)) {
    entriesFromText(content, null, entries, seen);
  } else {
    extractMarkdownLinks(content, entries, seen);
  }
  return entries;
}

export function syncNoteLinks(
  _db: Database.Database,
  userId: string,
  sourceNoteId: string,
  content: string,
): void {
  try {
    const links = extractNoteLinksFromContent(content).filter(
      (link) => !(link.targetNoteId === sourceNoteId.toLowerCase() && !link.targetBlockId),
    );
    noteLinksRepository.replaceLinksForSource(userId, sourceNoteId, links);
  } catch (error) {
    console.warn("[syncNoteLinks] failed:", error instanceof Error ? error.message : error);
  }
}

export function getBacklinks(
  _db: Database.Database,
  userId: string,
  targetNoteId: string,
  limit = 50,
) {
  return noteLinksRepository
    .getBacklinks(userId, targetNoteId, Math.min(Math.max(limit * 3, limit), 600))
    .filter((item) => hasPermission(resolveNotePermission(item.sourceNoteId, userId).permission, "read"))
    .slice(0, limit);
}
'''
Path("backend/src/lib/noteLinks.ts").write_text(NOTE_LINKS.rstrip() + "\n", encoding="utf-8")

replace_once(
    "backend/src/lib/noteBlocks.ts",
    '''  ensureNoteBlockTables(db);
  const parsed = contentFormat === "tiptap-json"
    ? parseTiptap(noteId, content)
    : parseMarkdown(noteId, content);''',
    '''  ensureNoteBlockTables(db);
  if (contentFormat === "html") {
    db.prepare("DELETE FROM note_blocks_index WHERE noteId = ?").run(noteId);
    return {
      content,
      contentText: content.replace(/<script[\\s\\S]*?<\\/script>/gi, " ").replace(/<style[\\s\\S]*?<\\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\\s+/g, " ").trim(),
      blocks: [],
      changed: false,
    };
  }
  const parsed = contentFormat === "tiptap-json"
    ? parseTiptap(noteId, content)
    : parseMarkdown(noteId, content);''',
    "HTML block indexing guard",
)
replace_once(
    "backend/src/lib/noteBlocks.ts",
    '''export function plainTextFromNoteContent(content: string, contentFormat: string): string {
  const parsed = contentFormat === "tiptap-json"
    ? parseTiptap("", content).candidates
    : parseMarkdown("", content).candidates;
  return parsed.map((block) => block.plainText).filter(Boolean).join("\\n\\n");
}''',
    '''export function plainTextFromNoteContent(content: string, contentFormat: string): string {
  if (contentFormat === "html") {
    return content.replace(/<script[\\s\\S]*?<\\/script>/gi, " ").replace(/<style[\\s\\S]*?<\\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\\s+/g, " ").trim();
  }
  const parsed = contentFormat === "tiptap-json"
    ? parseTiptap("", content).candidates
    : parseMarkdown("", content).candidates;
  return parsed.map((block) => block.plainText).filter(Boolean).join("\\n\\n");
}''',
    "HTML plain text guard",
)

replace_once(
    "backend/src/routes/blocks.ts",
    '''  const { note, userId } = required;
  const cached = readIdempotentResult(userId, body.operationId);''',
    '''  const { note, userId } = required;
  if (note.contentFormat === "html") {
    return c.json({ error: "HTML 笔记不支持块级写入", code: "BLOCK_FORMAT_UNSUPPORTED" }, 400);
  }
  const cached = readIdempotentResult(userId, body.operationId);''',
    "HTML block write guard",
)

CREATE_START = '''  // BACKLINKS-02: 维护 note_links 引用关系（写时维护）。'''
CREATE_END = '''  // Y1: SELECT 时 isFavorite 按当前用户动态计算；新建笔记当前用户尚未收藏，结果必为 0。'''
CREATE_REPLACEMENT = '''  // BLOCK-INDEX-01: 先规范化块 ID 和派生索引，再同步链接关系。
  // 顺序不能反过来，否则 Markdown 首次保存时 sourceBlockId 仍为空。
  let normalizedLinkContent: string | null = null;
  try {
    const stored = db.prepare("SELECT content, contentFormat FROM notes WHERE id = ?").get(id) as
      | { content: string; contentFormat: string }
      | undefined;
    if (stored) {
      const synced = syncNoteBlocks(db, id, stored.content || "", stored.contentFormat || "tiptap-json");
      normalizedLinkContent = synced.content;
      finalContent = synced.content;
    }
  } catch (e) {
    console.warn("[notes.post] syncNoteBlocks failed:", e instanceof Error ? e.message : e);
  }
  if (normalizedLinkContent !== null) {
    try {
      syncNoteLinks(db, userId, id, normalizedLinkContent);
    } catch (e) {
      console.warn("[notes.post] syncNoteLinks failed:", e instanceof Error ? e.message : e);
    }
  }

'''
replace_between("backend/src/routes/notes.ts", CREATE_START, CREATE_END, CREATE_REPLACEMENT, "create block/link order")

UPDATE_START = '''  // BACKLINKS-02: 同步 note_links 引用关系（仅在 content 字段被改动时）。'''
UPDATE_END = '''  // Y1: 返回值里 isFavorite 按当前用户动态计算（EXISTS favorites 表），'''
UPDATE_REPLACEMENT = '''  // BLOCK-INDEX-01: 内容更新时先规范化块 ID，再从规范化正文同步链接。
  if (body.content !== undefined && typeof body.content === "string") {
    let normalizedLinkContent = body.content;
    try {
      const stored = db.prepare("SELECT content, contentFormat FROM notes WHERE id = ?").get(id) as
        | { content: string; contentFormat: string }
        | undefined;
      if (stored) {
        const synced = syncNoteBlocks(db, id, stored.content || "", stored.contentFormat || "tiptap-json");
        normalizedLinkContent = synced.content;
        body.content = synced.content;
        body.contentText = synced.contentText;
      }
    } catch (e) {
      console.warn("[notes.put] syncNoteBlocks failed:", e instanceof Error ? e.message : e);
    }
    try {
      syncNoteLinks(db, userId, id, normalizedLinkContent);
    } catch (e) {
      console.warn("[notes.put] syncNoteLinks failed:", e instanceof Error ? e.message : e);
    }
  }

'''
replace_between("backend/src/routes/notes.ts", UPDATE_START, UPDATE_END, UPDATE_REPLACEMENT, "update block/link order")

TEST_APPEND = r'''

test("Markdown backlinks retain the source block ID", () => {
  const noteId = "55555555-5555-4555-8555-555555555555";
  const content = `Paragraph [[note:${targetId}#blk:blk_target|Target paragraph]]\n`;
  db.prepare(`INSERT INTO notes (id, userId, notebookId, title, content, contentText, contentFormat)
              VALUES (?, ?, ?, ?, ?, ?, ?)`)
    .run(noteId, owner, notebookId, "Markdown link", content, "", "markdown");
  const synced = syncNoteBlocks(db, noteId, content, "markdown");
  syncNoteLinks(db, owner, noteId, synced.content);
  const row = db.prepare(`
    SELECT sourceBlockId, targetBlockId FROM note_links
    WHERE sourceNoteId = ? AND targetNoteId = ?
  `).get(noteId, targetId) as { sourceBlockId: string | null; targetBlockId: string | null } | undefined;
  assert.ok(row);
  assert.equal(row?.sourceBlockId, synced.blocks[0].blockId);
  assert.equal(row?.targetBlockId, "blk_target");
});

test("HTML notes are never rewritten as Markdown blocks", () => {
  const noteId = "66666666-6666-4666-8666-666666666666";
  const content = "<!doctype html><html><body><p>Clipped article</p></body></html>";
  db.prepare(`INSERT INTO notes (id, userId, notebookId, title, content, contentText, contentFormat)
              VALUES (?, ?, ?, ?, ?, ?, ?)`)
    .run(noteId, owner, notebookId, "HTML clip", content, "Clipped article", "html");
  const synced = syncNoteBlocks(db, noteId, content, "html");
  assert.equal(synced.changed, false);
  assert.equal(synced.content, content);
  assert.equal(synced.blocks.length, 0);
  const stored = db.prepare("SELECT content FROM notes WHERE id = ?").get(noteId) as { content: string };
  assert.equal(stored.content, content);
});
'''
test_path = Path("backend/tests/knowledge-blocks.test.ts")
test_source = test_path.read_text(encoding="utf-8")
if 'test("Markdown backlinks retain the source block ID"' not in test_source:
    test_path.write_text(test_source.rstrip() + TEST_APPEND + "\n", encoding="utf-8")

print("issue 165 Markdown/HTML follow-up applied")
